leftnav:
- identifier: f3d0ebae-7083-4524-9b93-f688537a0317
  name: Page
  pageRef: /pages/page
  weight: 10
- identifier: 5eb7fe66-715e-4b3a-a951-42503e812b9c
  name: Embeds and Links
  pageRef: /pages/embeds-and-links
  weight: 20
- identifier: b91b7871-a083-4d20-bc48-9ac136807c95
  name: A resource list
  pageRef: /lists/resource-list
  weight: 30
- identifier: bf8257d0-bb35-41ce-9cdd-80b51150149d
  name: A video gallery
  pageRef: /video_galleries/video-gallery
  weight: 40
- identifier: 90ca54cb-b637-450d-90cd-88f13abae50b
  name: An image gallery
  pageRef: /pages/image-gallery
  weight: 50
- identifier: 31b116e3-698b-4e51-bd11-6817aceb8aff
  name: A Quiz
  pageRef: /pages/quiz
  weight: 60
- identifier: 51f2cc04-4f15-4aca-ac69-3ed31c879497
  name: An Image
  pageRef: /resources/file-19_jpg
  weight: 70
- identifier: 4b837f0b-8773-49f2-985a-7feeb195c87b
  name: A video
  pageRef: /resources/video_captioned_mp4
  weight: 80
- identifier: 48f6646f-f839-4e59-8aee-743062eb938c
  name: A document
  pageRef: /resources/file_new_pdf
  weight: 90
- identifier: b13e276a-509c-47ca-bd98-18e237b2bff2
  name: A Nest
  pageRef: /external-resources/a-nest_b13e276a-509c-47ca-bd98-18e237b2bff2
  weight: 100
- identifier: 81f5468c-9b98-4c0b-b69e-709c4f7c2ab8
  name: External Links
  pageRef: /pages/external-links
  weight: 110
- identifier: 1e4971b7-b7ea-42b6-98ae-483c80fa977a
  name: Page with RL and Embedded Images, text
  pageRef: /pages/resource-list-with-embedded-pictures
  weight: 120
- identifier: 1b895eb9-bd57-44bd-8809-573bcff55007
  name: Bird
  pageRef: /external-resources/bird_1b895eb9-bd57-44bd-8809-573bcff55007
  parent: b13e276a-509c-47ca-bd98-18e237b2bff2
  weight: 10
- identifier: 11ef13b8-c357-4a23-876f-63fdf39e988a
  name: Bird
  pageRef: /external-resources/bird_11ef13b8-c357-4a23-876f-63fdf39e988a
  parent: b13e276a-509c-47ca-bd98-18e237b2bff2
  weight: 20
- identifier: f24cc1d7-0985-4902-bf27-f9fc8a03e9b4
  name: Google.com
  pageRef: /external-resources/googlecom
  parent: 81f5468c-9b98-4c0b-b69e-709c4f7c2ab8
  weight: 10
- identifier: be7e0a90-ad6e-4085-80f2-2b6b6f4a77fe
  name: OCW
  pageRef: /external-resources/ocw-broken-backed-up-by-old-site
  parent: 81f5468c-9b98-4c0b-b69e-709c4f7c2ab8
  weight: 20
- identifier: 0c79321c-611c-4c6c-a7cf-9605704373c9
  name: OCW (no warning)
  pageRef: /external-resources/ocw-main
  parent: 81f5468c-9b98-4c0b-b69e-709c4f7c2ab8
  weight: 30
- identifier: 30aae89c-b155-4f97-8003-3bc1cc0a4bdb
  name: old external link
  pageRef: /external-resources/old-external-link_30aae89c-b155-4f97-8003-3bc1cc0a4bdb
  parent: 81f5468c-9b98-4c0b-b69e-709c4f7c2ab8
  weight: 40
- identifier: 3e670b86-52c1-49ee-9fd9-98629c28f26c
  name: Internal Link for ref
  pageRef: /resources/jellie8p_mp4
  parent: 81f5468c-9b98-4c0b-b69e-709c4f7c2ab8
  weight: 50
- identifier: dbc91fb4-91c0-4477-994c-fba9db49052a
  name: <iframe></iframe>
  pageRef: /external-resources/iframeiframe
  parent: 81f5468c-9b98-4c0b-b69e-709c4f7c2ab8
  weight: 60
- identifier: da6838a7-c03e-4f5c-95aa-dc0c59e17753
  name: https://google.com
  pageRef: /external-resources/httpsgooglecom
  parent: 81f5468c-9b98-4c0b-b69e-709c4f7c2ab8
  weight: 70
- identifier: cbf8be2f-9bf7-477a-ae1d-abb43520c67f
  name: Title Test
  pageRef: /external-resources/tiltle-test
  parent: 81f5468c-9b98-4c0b-b69e-709c4f7c2ab8
  weight: 80
- identifier: af2cedce-e0f7-4183-8eab-b309f7507d9a
  name: Egg
  pageRef: /external-resources/egg_af2cedce-e0f7-4183-8eab-b309f7507d9a
  parent: 1b895eb9-bd57-44bd-8809-573bcff55007
  weight: 10
- identifier: a59340d9-37f9-40a4-b4ab-8eeaaa061fa5
  name: Egg
  pageRef: /external-resources/egg_a59340d9-37f9-40a4-b4ab-8eeaaa061fa5
  parent: 1b895eb9-bd57-44bd-8809-573bcff55007
  weight: 20
